worker:
  image: siptg/worker
  restart: unless-stopped
  net: host
  volumes:
    - ./yate/conf:/etc/yate
    - ./ssl:/etc/yate/ssl:ro
    - ./yate/logs:/var/log/yate

nginx:
  image: nginx
  restart: unless-stopped
  net: host
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./ssl:/etc/nginx/ssl:ro
